# Generated by Django 4.0.2 on 2022-03-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=168)),
                ('birthday', models.TextField(max_length=20)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
