# Generated by Django 4.0.2 on 2022-04-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMDT', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='user_id',
            new_name='user',
        ),
    ]
