# Generated by Django 4.0.2 on 2022-03-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMDT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
