# Generated by Django 4.0.2 on 2022-04-22 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMDT', '0002_rename_user_id_shoppingcart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='price',
            new_name='total_price',
        ),
    ]
