# Generated by Django 4.0.2 on 2022-03-31 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMDT', '0004_category_order_product_remove_user_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderdetail',
            table='OrderDetail',
        ),
    ]
