# Generated by Django 4.0.2 on 2022-04-06 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMDT', '0005_alter_orderdetail_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='product_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TMDT.product'),
        ),
    ]
