# Generated by Django 4.0.2 on 2022-04-12 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TMDT', '0006_alter_productdetail_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TMDT.product', unique=True),
        ),
    ]
